Register and login form<br><br><br>

Register:<br><br>
<form action="/user/login/createUser/" method="post">
    Login: <input type="text" name="name" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    <input type="submit" value="Register">
</form>

<br>
<br>
<br>
Auth:<br><br>
<form action="/user/login/login/" method="post">
    Login: <input type="text" name="name" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    <input type="submit" value="Login">
</form>

<br>
<br>

<? if($this->error):?>
    Ошибка: <?=$this->error;?>
<? endif;?>
